development:
  recaptcha:
    public_key:
    private_key:
  s3:
    access_key_id:
    secret_access_key: ""
    bucket: subout-test
test:
  recaptcha:
    public_key:
    private_key:
  s3:
    access_key_id:
    secret_access_key: ""
    bucket: subout-test
subouttest:
  recaptcha:
    public_key: 
    private_key:
  s3:
    access_key_id:
    secret_access_key: ""
    bucket: subout-test
production:
  recaptcha:
    public_key:
    private_key:
  s3:
    access_key_id:
    secret_access_key: ""
    bucket: subout-production
